# Generated by Django 4.2.27 on 2026-04-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_systemconfig_email_suffix_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="icp_number",
            field=models.CharField(
                blank=True,
                help_text="ICP备案号，例如：京ICP备12345678号",
                max_length=100,
                null=True,
                verbose_name="ICP备案号",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="police_number",
            field=models.CharField(
                blank=True,
                help_text="公安备案号，例如：京公网安备 11010502000000号",
                max_length=100,
                null=True,
                verbose_name="公安备案号",
            ),
        ),
    ]
