# Generated by Django 4.2.27 on 2026-04-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_systemconfig_icp_number_systemconfig_police_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SystemStats",
        ),
    ]
