# Generated by Django 4.2.27 on 2026-04-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_remove_system_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="local_access_locked",
            field=models.BooleanField(
                default=False,
                help_text="启用后将禁止来自 localhost/127.0.0.1 的访问",
                verbose_name="禁止本地访问",
            ),
        ),
    ]
