# Generated by Django 4.2.27 on 2026-04-08 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0006_add_product_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="产品组的名称",
                        max_length=200,
                        verbose_name="产品组名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="产品组的详细描述，支持Markdown格式",
                        verbose_name="产品组描述",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="产品组在前端展示的顺序，数字越小越靠前",
                        verbose_name="显示顺序",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否在前端展示此产品组",
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "产品组",
                "verbose_name_plural": "产品组",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_group"], name="operations__product_981a27_idx"
            ),
        ),
        migrations.AddField(
            model_name="productgroup",
            name="auto_assign_providers",
            field=models.ManyToManyField(
                blank=True,
                help_text="这些提供商创建的产品将自动加入此产品组",
                related_name="auto_product_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="自动分配提供商",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_group",
            field=models.ForeignKey(
                blank=True,
                help_text="产品所属的产品组",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="operations.productgroup",
                verbose_name="产品组",
            ),
        ),
        migrations.AddIndex(
            model_name="productgroup",
            index=models.Index(
                fields=["is_active"], name="operations__is_acti_e01f52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productgroup",
            index=models.Index(
                fields=["display_order"], name="operations__display_2722d2_idx"
            ),
        ),
    ]
