# Generated by Django 4.2.27 on 2026-04-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0007_add_product_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountopeningrequest",
            name="requested_disk_capacity",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='用户额外申请的磁盘容量（MB），如 {"C:": 20480, "D:": 40960}',
                verbose_name="需求磁盘容量",
            ),
        ),
        migrations.AddField(
            model_name="cloudcomputeruser",
            name="disk_quota",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='用户的磁盘配额配置（MB），如 {"C:": 10240, "D:": 20480}',
                verbose_name="磁盘配额",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="allow_extra_quota_disks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='允许用户在申请时额外申请容量的磁盘列表，如 ["C:", "D:"]',
                verbose_name="允许额外申请容量的磁盘",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="default_disk_quota",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='每个磁盘的默认配额大小（MB），如 {"C:": 10240, "D:": 20480}',
                verbose_name="默认磁盘配额",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="enable_disk_quota",
            field=models.BooleanField(
                default=False,
                help_text="是否启用磁盘配额管理，启用后将自动为新用户设置磁盘配额",
                verbose_name="启用磁盘配额管理",
            ),
        ),
    ]
