# Generated by Django 4.2.27 on 2026-04-06 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hosts", "0005_host_connection_type_alter_host_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="administrators",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_hosts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="授权管理员",
            ),
        ),
    ]
