# Generated by Django 4.2.27 on 2026-04-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hosts", "0006_host_administrators"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostgroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_hostgroups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
    ]
