# Generated by Django 4.2.27 on 2026-04-07 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hosts", "0007_add_hostgroup_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="providers",
            field=models.ManyToManyField(
                blank=True,
                help_text="由超级管理员分配的提供商用户，提供商可以管理此主机",
                related_name="provider_hosts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="管理提供商",
            ),
        ),
        migrations.AddField(
            model_name="hostgroup",
            name="providers",
            field=models.ManyToManyField(
                blank=True,
                help_text="由超级管理员分配的提供商用户，提供商可以管理此主机组",
                related_name="provider_hostgroups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="管理提供商",
            ),
        ),
    ]
